from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np


@dataclass(slots=True)
class SimpleAtoms:
    symbols: list[str]
    positions: np.ndarray
    cell: np.ndarray | None = None
    pbc: tuple[bool, bool, bool] = (False, False, False)


def write_extxyz(path: str | Path, symbols: list[str], positions: np.ndarray, cell: np.ndarray | None = None, pbc: tuple[bool, bool, bool] = (False, False, False)) -> None:
    target = Path(path)
    try:
        from ase import Atoms
        from ase.io import write

        atoms = Atoms(symbols=symbols, positions=positions, cell=cell, pbc=pbc)
        write(target, atoms, format="extxyz")
        return
    except ModuleNotFoundError:
        pass
    lines = [str(len(symbols)), f"Properties=species:S:1:pos:R:3 pbc=\"{' '.join('T' if flag else 'F' for flag in pbc)}\""]
    for symbol, position in zip(symbols, positions):
        lines.append(f"{symbol} {position[0]:.16f} {position[1]:.16f} {position[2]:.16f}")
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")


def read_extxyz(path: str | Path) -> SimpleAtoms:
    source = Path(path)
    try:
        from ase.io import read

        atoms = read(source)
        return SimpleAtoms(
            symbols=atoms.get_chemical_symbols(),
            positions=np.asarray(atoms.positions, dtype=float),
            cell=None if atoms.cell is None else np.asarray(atoms.cell.array, dtype=float),
            pbc=tuple(bool(value) for value in atoms.pbc),
        )
    except ModuleNotFoundError:
        pass
    lines = source.read_text(encoding="utf-8").splitlines()
    natoms = int(lines[0].strip())
    symbols: list[str] = []
    positions = np.zeros((natoms, 3), dtype=float)
    for index, line in enumerate(lines[2 : 2 + natoms]):
        parts = line.split()
        symbols.append(parts[0])
        positions[index] = np.asarray([float(parts[1]), float(parts[2]), float(parts[3])], dtype=float)
    return SimpleAtoms(symbols=symbols, positions=positions)


def write_xyz(path: str | Path, symbols: list[str], positions: np.ndarray) -> None:
    target = Path(path)
    lines = [str(len(symbols)), "generated by GMD_active_learning"]
    for symbol, position in zip(symbols, positions):
        lines.append(f"{symbol} {position[0]:.16f} {position[1]:.16f} {position[2]:.16f}")
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_poscar(path: str | Path, symbols: list[str], positions: np.ndarray, cell: np.ndarray | None = None) -> None:
    target = Path(path)
    species: dict[str, int] = {}
    for symbol in symbols:
        species[symbol] = species.get(symbol, 0) + 1
    lattice = np.eye(3, dtype=float) * 20.0 if cell is None else np.asarray(cell, dtype=float)
    grouped_positions = [positions[index] for symbol in species for index, atom_symbol in enumerate(symbols) if atom_symbol == symbol]
    lines = [
        "GMD_active_learning",
        "1.0",
        *(f"{row[0]:.16f} {row[1]:.16f} {row[2]:.16f}" for row in lattice),
        " ".join(species.keys()),
        " ".join(str(count) for count in species.values()),
        "Cartesian",
        *(f"{position[0]:.16f} {position[1]:.16f} {position[2]:.16f}" for position in grouped_positions),
    ]
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
